apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: sample-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::296336226405:role/sample-app-backend-sa-role_lsy05
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: sample-app
type: Opaque
stringData:
  S3_BUCKET_NAME: "sample-app-dev-files-296336226405-v2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: backend
          image: 296336226405.dkr.ecr.us-east-2.amazonaws.com/sample-app/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: S3_BUCKET_NAME
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: sample-app
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080