apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awseks-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/siyeon04/awsskback.git'
    targetRevision: HEAD
    path: 'manifests/backend'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true